"use client";
import {useState,useEffect} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {BriefcaseBusiness,GraduationCap,Layers,Mail,MapPin,Download,Presentation,Phone,Check,Building2,CalendarDays,ChevronLeft,ChevronRight,X,SlidersHorizontal} from "lucide-react";
import {Choice} from "@/components/choice";
import type {Profile} from "@/lib/profile";
const sections=[['resumen','Perfil'],['experiencia','Experiencia'],['formacion','Formación y certificados'],['competencias','Competencias'],['servicios','Servicios']];
const date=(s:string)=>new Date(s+'-02').toLocaleDateString('es-PE',{month:'short',year:'numeric'});
export default function Dashboard({profile:p}:{profile:Profile}){
 const [tab,setTab]=useState('resumen'),[sector,setSector]=useState('Todos'),[area,setArea]=useState('Todas'),[query,setQuery]=useState(''),[cert,setCert]=useState<Profile['certs'][number]|null>(null),[present,setPresent]=useState(false),[certFilter,setCertFilter]=useState('Todos');
 const sorted=[...p.roles].sort((a,b)=>b.start.localeCompare(a.start));const firstYear=sorted[sorted.length-1]?.start.slice(0,4)||'';const lastDate=sorted.map(r=>r.end).sort().at(-1)||'';
 const roles=sorted.filter(r=>(sector==='Todos'||r.sector===sector)&&(area==='Todas'||r.area===area)&&`${r.company} ${r.role}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{function key(e:KeyboardEvent){if(!present)return;if(e.key==='Escape')setPresent(false);if(['ArrowRight','ArrowLeft'].includes(e.key))setTab(t=>sections[(sections.findIndex(s=>s[0]===t)+(e.key==='ArrowRight'?1:4))%5][0]);}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[present]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();Promise.resolve(ctx.registerTool({name:'filter_professional_experience',description:'Muestra y filtra la trayectoria profesional por sector.',inputSchema:{type:'object',properties:{sector:{type:'string',enum:['Todos','Público','Privado']}},required:['sector'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(v:any)=>{if(!['Todos','Público','Privado'].includes(v?.sector))throw Error('Sector inválido');setTab('experiencia');setSector(v.sector);setArea('Todas');setQuery('');return {sector:v.sector,count:p.roles.filter(r=>v.sector==='Todos'||r.sector===v.sector).length}}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[p]);
 const jobs=(list:Profile['roles'])=>list.map(r=><article className="job" key={r.id}><div className="job-date">{date(r.start)}<span>{date(r.end)}</span></div><div className="job-main"><div className="job-head"><h3>{r.company}</h3><span className="chip">{r.sector}</span></div><h4>{r.role}</h4><details><summary>Funciones y aportes</summary><ul>{r.details.map((d,i)=><li key={i}>{d}</li>)}</ul></details></div></article>);
 return <div className={present?'site presentation':'site'}><header className="topbar"><a href="./" className="brand"><span>EV</span><div>ESTEFANIA VELASQUEZ VINCES<small>ADMINISTRACIÓN & GESTIÓN</small></div></a><div className="top-actions"><button className="btn ghost" onClick={()=>setPresent(!present)}><Presentation size={17}/>{present?'Salir de presentación':'Modo presentación'}</button><a className="btn dark" href={p.cv} download><Download size={17}/>Descargar CV</a></div></header><main><section className="profile-header"><div className="identity"><div className="portrait"><img src="./estefania.jpeg" alt="Estefania Velasquez Vinces"/></div><div><p className="eyebrow">PERFIL PROFESIONAL</p><h1>{p.name}</h1><p className="qualification">{p.title}</p><p className="location"><MapPin size={15}/>{p.location}<span>·</span>Sector público y privado</p></div></div><div className="contact-compact"><a className="btn teal" href={'https://wa.me/'+p.phone} target="_blank" rel="noreferrer"><Phone size={17}/>Conversemos</a><a className="mail" href={'mailto:'+p.email}><Mail size={16}/>Enviar correo</a></div></section>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs" variant="line">{sections.map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList>
 <TabsContent value="resumen"><div className="overview-grid"><section className="intro-panel"><p className="eyebrow">ORDEN, COORDINACIÓN Y SEGUIMIENTO</p><h2>Una gestión que conecta<br/><em>personas y procesos.</em></h2><p>{p.summary}</p><div className="specialties"><span>Alta Dirección</span><span>Gestión documentaria</span><span>Administración</span></div></section><aside className="at-glance"><p className="eyebrow">TRAYECTORIA EN PERSPECTIVA</p><div className="metric"><strong>{firstYear}–{lastDate.slice(0,4)}</strong><span>Trayectoria documentada en el CV</span></div><div className="metric-row"><div><strong>{p.roles.length}</strong><span>Experiencias laborales</span></div><div><strong>{new Set(p.roles.map(r=>r.company)).size}</strong><span>Organizaciones</span></div></div><p className="note">Períodos según CV · última experiencia: {lastDate?date(lastDate):""}</p></aside></div><div className="section-head"><div><p className="eyebrow">EXPERIENCIA RECIENTE</p><h2>Al servicio de la gestión</h2></div><button className="text-button" onClick={()=>setTab('experiencia')}>Ver trayectoria completa</button></div><div className="recent-grid">{sorted.slice(0,3).map((r,i)=><article className="recent-card" key={r.id}><div className="card-top"><span className="icon-square"><Building2 size={21}/></span><span className="muted">0{i+1}</span></div><h3>{r.company}</h3><p>{r.role}</p><footer>{date(r.start)} — {date(r.end)}</footer></article>)}</div><div className="tools-strip"><strong>Herramientas de gestión</strong>{['SIAF','SIGA','SGD','Microsoft Office'].map(t=><span key={t}>{t}</span>)}</div></TabsContent>
 <TabsContent value="experiencia"><div className="section-head"><div><p className="eyebrow">RECORRIDO PROFESIONAL</p><h2>Experiencia con perspectiva</h2></div><span className="muted">{roles.length} experiencias</span></div><div className="filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Entidad o puesto"/></label><fieldset><legend>Sector</legend>{['Todos','Público','Privado'].map(s=><button key={s} className={'filter '+(s===sector?'selected':'')} onClick={()=>setSector(s)}>{s}</button>)}</fieldset><label>Especialidad<Choice value={area} onChange={setArea} options={["Todas",...new Set(p.roles.map(r=>r.area))]} label="Especialidad"/></label><button className="text-button" onClick={()=>{setQuery('');setSector('Todos');setArea('Todas')}}>Restablecer</button></div><div className="timeline">{roles.length?jobs(roles):<p className="empty">No hay experiencias con estos filtros. Prueba otra búsqueda.</p>}</div><p className="note">Las fechas se presentan como figuran en el CV. Los períodos simultáneos no se suman como años de experiencia.</p></TabsContent>
 <TabsContent value="formacion"><div className="section-head"><div><p className="eyebrow">APRENDIZAJE Y ESPECIALIZACIÓN</p><h2>Formación que respalda la práctica</h2></div><span className="muted">{p.certs.length} documentos</span></div><div className="degree-banner"><GraduationCap size={40}/><div><h3>{p.title}</h3><p>Formación y especialización profesional</p></div></div><div className="filter-row">{['Todos',...new Set(p.certs.map(c=>c.category))].map(c=><button key={c} className={'filter '+(certFilter===c?'selected':'')} onClick={()=>setCertFilter(c)}>{c}</button>)}</div><div className="certificate-grid">{p.certs.filter(c=>certFilter==='Todos'||c.category===certFilter).map(c=><button className="certificate" onClick={()=>setCert(c)} key={c.id}><div className="certificate-thumb">{c.url.startsWith('/api/')?<GraduationCap size={60}/>:<img src={c.url} alt={'Vista de '+c.title} loading="lazy"/>}</div><div className="certificate-body"><span className="eyebrow">{c.issuer} · {c.year}</span><h3>{c.title}</h3><span className="view-label">Ver documento</span></div></button>)}</div></TabsContent>
 <TabsContent value="competencias"><div className="section-head"><div><p className="eyebrow">CAPACIDADES PROFESIONALES</p><h2>Herramientas y criterio administrativo</h2></div></div><div className="skills-grid">{p.skills.map((s,i)=><article className="skill-card" key={i}><span className="skill-index">0{i+1}</span><Layers size={24}/><h3>{s.name}</h3><p>{s.detail}</p></article>)}</div><div className="two-col"><article className="plain-card"><h3>Coordinación y personas</h3><ul><li>Coordinación interáreas e interinstitucional.</li><li>Apoyo en supervisión de personal administrativo.</li><li>Organización de reuniones y agendas ejecutivas.</li></ul></article><article className="plain-card"><h3>Comunicación y análisis</h3><ul><li>Redacción de oficios, informes, actas y memorandos.</li><li>Cuadros de control y seguimiento de compromisos.</li><li>Inglés: nivel básico, según CV.</li></ul></article></div></TabsContent>
 <TabsContent value="servicios"><div className="section-head"><div><p className="eyebrow">COLABORACIÓN PROFESIONAL</p><h2>Apoyo administrativo para tu organización</h2></div></div><p className="lead">Para oportunidades laborales y servicios independientes en administración y coordinación.</p><div className="recent-grid">{[['Gestión administrativa','Organización de requerimientos, coordinación de agendas, seguimiento de compromisos y apoyo operativo.'],['Gestión documentaria','Registro, clasificación, seguimiento de expedientes, digitalización y organización del archivo.'],['Soporte a direcciones','Preparación de documentos ejecutivos, ayudas de memoria y coordinación con equipos y áreas.']].map(([t,d])=><article className="service-card" key={t}><Check size={25}/><h3>{t}</h3><p>{d}</p></article>)}</div><div className="contact-banner"><div><p className="eyebrow">HABLEMOS DE TU PRÓXIMO PROYECTO</p><h2>Una conversación puede ser<br/>el inicio de una buena colaboración.</h2></div><div><a className="btn teal" href={'https://wa.me/'+p.phone} target="_blank" rel="noreferrer">WhatsApp · +{p.phone}</a><a href={'mailto:'+p.email}>{p.email}</a></div></div></TabsContent>
 </Tabs></main><footer className="site-footer"><span>© {new Date().getFullYear()} {p.fullName}</span><span>Lima, Perú · Referencias a solicitud</span><a href="https://github.com/Doccs23/estefania-velasquez-vinces" target="_blank" rel="noreferrer">Administrar perfil</a></footer>{present&&<div className="presentation-controls"><button aria-label="Sección anterior" onClick={()=>setTab(sections[(sections.findIndex(s=>s[0]===tab)+4)%5][0])}><ChevronLeft/></button><span>{sections.findIndex(s=>s[0]===tab)+1} / 5 · {sections.find(s=>s[0]===tab)?.[1]}</span><button aria-label="Sección siguiente" onClick={()=>setTab(sections[(sections.findIndex(s=>s[0]===tab)+1)%5][0])}><ChevronRight/></button><button aria-label="Salir de presentación" onClick={()=>setPresent(false)}><X/></button></div>}
 <Dialog open={!!cert} onOpenChange={v=>!v&&setCert(null)}><DialogContent className="certificate-dialog"><DialogTitle>{cert?.title}</DialogTitle><DialogDescription>{cert?.issuer} · {cert?.year} · Copia para consulta pública</DialogDescription>{cert&&!cert.url.startsWith("/api/")&&<img src={cert.url} alt={cert.title}/>}<a className="btn dark" href={cert?.url} target="_blank" rel="noreferrer">Abrir documento</a></DialogContent></Dialog></div>
}
